version: "3"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    container_name: mysql
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d  #初期データをマウントする場所
    image: mysql_db # イメージの名前
    environment:
      - MYSQL_ROOT_PASSWORD=mysql   #コンテナ内のMySQLを起動する際のパスワードを設定
    ports:
      - 3306:3306
    networks:
        - default
        - shared-network
networks:
    shared-network:
        external: true
      